name: Rust

on:
  push:
    paths:
      - 'solutions/Rust/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'solutions/Rust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build 
      run: cargo build --verbose --manifest-path solutions/Rust/AdventOfCode/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path solutions/Rust/AdventOfCode/Cargo.toml
